export const source = {
  cardFantasyMage: '../src/app/assets/cardFantasyMageTest.png',
  game: {
    logo: '../src/images/logo.png',
    notebook: {
      small: '../src/app/assets/game/notebook/small.jpg',
      small2: '../src/app/assets/game/notebook/small2.jpg',
    },
    question: {
      black: '../src/app/assets/game/question/qBlackBg.png',
      england: '../src/app/assets/game/question/qEnglandBg.png',
      modern: '../src/app/assets/game/question/qModernBg.png',
      fantasy: '../src/app/assets/game/question/qFantasyBg.png',
    },
    bg: {
      base: '../src/app/assets/game/bg/bgBase.jpg',
      england: '../src/app/assets/game/bg/bgEngland.jpg',
      fantasy: '../src/app/assets/game/bg/bgFantasy.jpg',
      modern: '../src/app/assets/game/bg/bgModern.jpg',
    },
    memory: {
      england: '../src/app/assets/game/memory/england.png',
      englandH: '../src/app/assets/game/memory/englandH.png',
      fantasy: '../src/app/assets/game/memory/fantasy.png',
      fantasyH: '../src/app/assets/game/memory/fantasyH.png',
      modern: '../src/app/assets/game/memory/modern.png',
      modernH: '../src/app/assets/game/memory/modernH.png',
    },
    cards: {
      back: [
        '../src/app/assets/game/cards/back/backQ13.png',
        '../src/app/assets/game/cards/back/backQ245.png'
      ],
      england: {
        profession: [
          '../src/app/assets/game/cards/england/profession/1.jpg',
          '../src/app/assets/game/cards/england/profession/2.jpg',
          '../src/app/assets/game/cards/england/profession/3.jpg',
          '../src/app/assets/game/cards/england/profession/4.jpg',
          '../src/app/assets/game/cards/england/profession/5.jpg',
          '../src/app/assets/game/cards/england/profession/6.jpg',
          '../src/app/assets/game/cards/england/profession/7.jpg',
          '../src/app/assets/game/cards/england/profession/8.jpg',
          '../src/app/assets/game/cards/england/profession/9.jpg',
          '../src/app/assets/game/cards/england/profession/10.jpg',
          '../src/app/assets/game/cards/england/profession/11.jpg',
          '../src/app/assets/game/cards/england/profession/12.jpg',
          '../src/app/assets/game/cards/england/profession/13.jpg',
          '../src/app/assets/game/cards/england/profession/14.jpg',
        ],
        secrets: [
          '../src/app/assets/game/cards/england/secrets/1.jpg',
          '../src/app/assets/game/cards/england/secrets/2.jpg',
          '../src/app/assets/game/cards/england/secrets/3.jpg',
          '../src/app/assets/game/cards/england/secrets/4.jpg',
          '../src/app/assets/game/cards/england/secrets/5.jpg',
          '../src/app/assets/game/cards/england/secrets/6.jpg',
          '../src/app/assets/game/cards/england/secrets/7.jpg',
          '../src/app/assets/game/cards/england/secrets/8.jpg',
          '../src/app/assets/game/cards/england/secrets/9.jpg',
          '../src/app/assets/game/cards/england/secrets/10.jpg',
          '../src/app/assets/game/cards/england/secrets/11.jpg',
          '../src/app/assets/game/cards/england/secrets/12.jpg',
          '../src/app/assets/game/cards/england/secrets/13.jpg',
          '../src/app/assets/game/cards/england/secrets/14.jpg',
        ]
      },
      fantasy: {
        profession: [
          '../src/app/assets/game/cards/fantasy/profession/1.jpg',
          '../src/app/assets/game/cards/fantasy/profession/2.jpg',
          '../src/app/assets/game/cards/fantasy/profession/3.jpg',
          '../src/app/assets/game/cards/fantasy/profession/4.jpg',
          '../src/app/assets/game/cards/fantasy/profession/5.jpg',
          '../src/app/assets/game/cards/fantasy/profession/6.jpg',
          '../src/app/assets/game/cards/fantasy/profession/7.jpg',
          '../src/app/assets/game/cards/fantasy/profession/8.jpg',
          '../src/app/assets/game/cards/fantasy/profession/9.jpg',
          '../src/app/assets/game/cards/fantasy/profession/10.jpg',
          '../src/app/assets/game/cards/fantasy/profession/11.jpg',
          '../src/app/assets/game/cards/fantasy/profession/12.jpg',
          '../src/app/assets/game/cards/fantasy/profession/13.jpg',
          '../src/app/assets/game/cards/fantasy/profession/14.jpg',
        ],
        secrets: [
          '../src/app/assets/game/cards/fantasy/secrets/1.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/2.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/3.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/4.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/5.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/6.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/7.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/8.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/9.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/10.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/11.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/12.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/13.jpg',
          '../src/app/assets/game/cards/fantasy/secrets/14.jpg',
        ]
      },
      modern: {
        profession: [
          '../src/app/assets/game/cards/modern/profession/1.jpg',
          '../src/app/assets/game/cards/modern/profession/2.jpg',
          '../src/app/assets/game/cards/modern/profession/3.jpg',
          '../src/app/assets/game/cards/modern/profession/4.jpg',
          '../src/app/assets/game/cards/modern/profession/5.jpg',
          '../src/app/assets/game/cards/modern/profession/6.jpg',
          '../src/app/assets/game/cards/modern/profession/7.jpg',
          '../src/app/assets/game/cards/modern/profession/8.jpg',
          '../src/app/assets/game/cards/modern/profession/9.jpg',
          '../src/app/assets/game/cards/modern/profession/10.jpg',
          '../src/app/assets/game/cards/modern/profession/11.jpg',
          '../src/app/assets/game/cards/modern/profession/12.jpg',
          '../src/app/assets/game/cards/modern/profession/13.jpg',
          '../src/app/assets/game/cards/modern/profession/14.jpg',
        ],
        secrets: [
          '../src/app/assets/game/cards/modern/secrets/1.jpg',
          '../src/app/assets/game/cards/modern/secrets/2.jpg',
          '../src/app/assets/game/cards/modern/secrets/3.jpg',
          '../src/app/assets/game/cards/modern/secrets/4.jpg',
          '../src/app/assets/game/cards/modern/secrets/5.jpg',
          '../src/app/assets/game/cards/modern/secrets/6.jpg',
          '../src/app/assets/game/cards/modern/secrets/7.jpg',
          '../src/app/assets/game/cards/modern/secrets/8.jpg',
          '../src/app/assets/game/cards/modern/secrets/9.jpg',
          '../src/app/assets/game/cards/modern/secrets/10.jpg',
          '../src/app/assets/game/cards/modern/secrets/11.jpg',
          '../src/app/assets/game/cards/modern/secrets/12.jpg',
          '../src/app/assets/game/cards/modern/secrets/13.jpg',
          '../src/app/assets/game/cards/modern/secrets/14.jpg',
        ]
      }
    }
  }
}

export const questions = {
  england: ['Чем тебе больше всего\nдосадили родственники?', 'Ты получил приглашение\nна аудиенцию во дворец.\nТвои действия?', 'Что тебе запомнилось\nв утренних газетах?'],
  modern: ['Какую суперспособность\nты бы хотел иметь?', 'В твоём доме отключили\nэлектричество. Твои действия?', 'Звонок. Босс хочет\nтебя видеть через 15 минут.\nТвои действия?'],
  fantasy: ['Тебя преследует монстр.\nТвои действия?', 'Какому заклинанию\nты хотел бы научиться?', 'С какой целью ты бы\nотправился в приключение?'],
  black: [
    'В каком ты настроении?', 'За что тебя наградили?', 'Какой была твоя последняя\nпрочитанная книга?', 
    'О чём ты мечтаешь?', 'Что бы ты заказал на обед?', 'Куда бы ты поехал\nпрямо сейчас?', 
    'Что привлекло твоё внимание\nпо дороге сюда?', 'К тебе ворвались грабители.\nТвои действия?', 'Как выглядит твоё жилище?',
    'Какой у тебя питомец?', 'Что у тебя с собой?', 'Чего ты боишься?',
    'Какое у тебя телосложение?', 'Что на тебе надето?', 'Какие у тебя руки?',
    'Какое ты производишь\nпервое впечатление?', 'Какая на тебе обувь?', 'Как выглядят твоё лицо\nи твоя причёска?'
  ],
}

export const cards = {
  england: {
    profession: [
      'Почтальон',
      'Портной',
      'Адмирал',
      'Пекарь',
      'Банкир',
      'Поэт',
      'Механик',
      'Полицейский',
      'Продавец газет',
      'Частный сыщик',
      'Кучер',
      'Химик',
      'Фокусник',
      'Путешественник',
    ],
    secrets: [
      'Подделываю\nденьги',
      'Клептоман',
      'Отравил дядю\nради наследства',
      'Непьющий',
      'Болен\nтропической\nлихорадкой',
      'Рассеянный',
      'Посещаю\nпубличный дом',
      'Блохастый',
      'Скрываю\nблагородное\nпроисхождение',
      'Держу дома\nзмей',
      'Живу двойной\nжизнью',
      'Строю\nподводную лодку',
      'Уволен с работы',
      'Провожу\nспиритические\nсеансы',
    ]
  },
  modern: {
    profession: [
      'Стилист',
      'Таксист',
      'Строитель',
      'Журналист',
      'Дрессировщик',
      'Следователь',
      'Блогер',
      'Электрик',
      'Кинорежиссер',
      'Программист',
      'Фитнес-тренер',
      'Дизайнер',
      'Бармен',
      'Врач\nскорой помощи'
    ],
    secrets: [
      'Верю в теорию\nзаговора',
      'Многодетный',
      'Состою в ОПГ',
      'Жертва шантажа',
      'Снимаю видео\nс котиками',
      'Бывают\nгаллюцинации',
      'Навещаю\nродственника\nв тюрьме',
      'Информатор\nспецслужб',
      'Страдаю\nот аллергии\nна шерсть',
      'Шопоголик',
      'Политический\nактивист',
      'Живу в кредит',
      'Интернет-тролль',
      'Незаконно\nрисую граффити'
    ]
  },
  fantasy: {
    profession: [
      'Палач',
      'Бард',
      'Стражник',
      'Боевой маг',
      'Драконий\nвсадник',
      'Глашатай',
      'Конюх',
      'Инквизитор',
      'Шаман',
      'Трактирщик',
      'Кузнец',
      'Берсерк',
      'Разбойник',
      'Некромант'
    ],
    secrets: [
      'Превратил\nбрата в овцу',
      'Воскрес\nиз мертвых',
      'Считаю, что\nволшебников\nне существует',
      'Охочусь\nна оборотней',
      'Нашел лампу\nс джином',
      'Одержим\nдемоном',
      'Чемпион\nрыцарского\nтурнира',
      'Прибыл из\nдругого мира',
      'Убежден,\nчто мой сосед -\nвампир',
      'Убил сборщика\nналогов',
      'Купил\nпроклятый меч',
      'Прихвостень\nТемного\nвластелина',
      'Сплю в гробу',
      'Ищу жертву\nдля ритуала'
    ]
  }
}
