export const enum HTTP_METHOD {
  GET = 'GET',
  POST = 'POST',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
  PUT = 'PUT',
}

export const enum KEYS {
  Control = 'Control',
  Shift = 'Shift',
  Alt = 'Alt',
  Meta = 'Meta',
  Win = 'Win',
  PageUp = 'PageUp',
  PageDown = 'PageDown',
  Home = 'Home',
  End = 'End',
  Delete = 'Delete',
  Insert = 'Insert',
  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
  PrintScreen = 'PrintScreen',
  Scroll = 'Scroll',
  Escape = 'Escape',
  CapsLock = 'CapsLock',
  Tab = 'Tab',
  Left = 'ArrowLeft',
  Right = 'ArrowRight',
  Up = 'ArrowUp',
  Down = 'ArrowDown',
  Backspace = 'Backspace',
  Enter = 'Enter',
}
